travis:
  secure:
    BINSTAR_TOKEN: yxTiSIDfm4MuiJjFxRWu69cb7jZR4K6QMvlQ2X60AN3hQLM6BbEUnnnmujddfPCjdRc7OfxeTQsgF61dxJRGhrTHcASCHYB2iWb5nMT7NmUNs0L+pQBldoLDFgHk0OgVuOU3bkWmDaTfcMelyrXzS+Eem40V5RMU5xYRMQxfOB61nwCN8wH+bieiO5cBiMYHeLcKOmjdNyVh0Yc13di1E7swFbG559CBTP1HHRnPFGBpQ/epvv9kQBFBx6NHdqYwF6X2398I1uDejq+zJb5WGn6Am/AQFWSTz80vqqnLOk++JfW3s3I6FWpK7x4766KFjqJI18bTtkWaAw3Qxe7NBI3gGjauxQlIJtsYFRypU6qF+9zm8qPPSJXTN6wB1ZT5+qCSj8s8xLV8Rr2AwH6itiBFwUIFkmdUQXrIRcpCq14M88inJjuZa1GapTOq4DVlAfRDlkLg/YKERIfbcr9AqD6qsfiEyB8x1+HADq4wg+L9a3AM7wwXI/T1ArTIM6BzCWgW55gvo8v3dvgRWnuyLYvSC2hmS4a7mylx74Px6vTjmifkDsBQ3w9E8XEtskcB/AJWtJJs8yCf5526oz2Ix+KouosRo09rOvlA7AnRjwTZoNb7oJpDKDuL9Vz6EsiQybTvVIyBtdwq4FD0WY1Cl2vpI2XelEz6v6GbkE2/izM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1

upload_on_branch: master
conda_forge_output_validation: false
